/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package RegistoFolgas;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.ParseException;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.text.MaskFormatter;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPasswordField;

/**
 *
 * @author anasi
 */
public class Login extends javax.swing.JDialog {
    private static Connection con;
     private static final String driver="org.sqlite.JDBC";
     private static final String url="jdbc:sqlite:data/AgendamentoFolgas.db";
     private PreparedStatement statement=null;
     private ResultSet resultSet =null;
    private JLabel jLabelNome;
    private JLabel jLabelFuncionario;
    private static final String GESTOR="Rui Vilaça";
     
    
     
     public void connector() {
    con=null;
    try{
        
       
        Class.forName(driver);
        con=(Connection)DriverManager.getConnection(url);
        if(con!=null){
        
        }
    }
    catch (ClassNotFoundException |SQLException e){

        JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabelNome=new JLabel();
        jLabelFuncionario=new JLabel();
        connector();
        

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                
            }
        });
    }

    

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jLabelRegisto = new javax.swing.JLabel();
        jFormattedTextFieldUtilizador = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 204));
        jLabel1.setText("Take a Break!");

        jLabel2.setText("Com o Take a Break você  pode marcar as suas ausências, receber a notificação de aprovação ou rejeição, visulizar as ausências aprovadas e ainda poder saber a remuneração que irá receber pela ausência!");

        jLabel3.setText("Para aceder a Take a Break! tem de fazer o seu login ou registar-se na aplicação caso não tenha uma conta associada.");

        jLabel4.setText("Nome de Utilizador");

        jLabel5.setText("Palavra-Passe");

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jButtonEntrar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEntrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jLabelRegisto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelRegisto.setForeground(new java.awt.Color(102, 153, 255));
        jLabelRegisto.setText("Caso não tenha uma conta associada, clique aqui para fazer seu registo!");
        jLabelRegisto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistoMouseClicked(evt);
            }
        });

        jLabel6.setText("O Take a Break faz isso automaticamente sem precisar do seu chefe!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldUtilizador)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabelRegisto, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEntrar)
                .addGap(283, 283, 283))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldUtilizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEntrar)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelRegisto)
                        .addGap(77, 77, 77))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
       setVisible(false);
       Folgas folgas=new Folgas(jLabelNome,jLabelFuncionario);
       folgas.setVisible(false);
       Registo registo=new Registo();
       registo.setVisible(false);
    }//GEN-LAST:event_closeDialog

    private void jLabelRegistoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistoMouseClicked
        setVisible(false);
        Registo registo=new Registo();
        registo.setVisible(true);
        Folgas folgas=new Folgas(jLabelNome,jLabelFuncionario);
        folgas.setVisible(false);
        
        
    }//GEN-LAST:event_jLabelRegistoMouseClicked

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        
        if(autenticarUsuario()){
        
        setVisible(false);
        Folgas folgas=new Folgas(jLabelNome,jLabelFuncionario);
        String nomeUsuario=autenticarUsuario1(folgas);
        folgas.setVisible(true);
        Registo registo=new Registo();
        registo.setVisible(false);
        
        
        
        }
        else{
            JOptionPane.showMessageDialog(this, "Credenciais inválidas!","Erro",JOptionPane.ERROR_MESSAGE);
        }
    
        
        

        
        
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed
   
    public boolean autenticarUsuario() {
        String email = jFormattedTextFieldUtilizador.getText().trim();
    String senha = String.valueOf(jPasswordField.getPassword());

    // Consulta SQL para buscar o usuário com base no email e na senha
    String sql = "SELECT * FROM Funcionário WHERE Email = ? AND Password = ?";

    try {
        // Preparar a consulta
        PreparedStatement statement = con.prepareStatement(sql);
        statement.setString(1, email);
        statement.setString(2, senha);

        // Executar a consulta
        resultSet = statement.executeQuery();

        // Verificar se o usuário foi encontrado
        return resultSet.next();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao autenticar usuário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }finally{
        try{
            resultSet.close();
            statement.close();
            con.close();
        }catch(Exception e){
        }
        
        }

    // Se chegou aqui, significa que ocorreu algum erro ou as credenciais são inválidas
    return false;
    
    
    

    }
   public String autenticarUsuario1(Folgas folgas){
       String email = jFormattedTextFieldUtilizador.getText().trim();
    String senha = String.valueOf(jPasswordField.getPassword());

    // Consulta SQL para buscar o usuário com base no email e na senha
    String sql = "SELECT Nome FROM Funcionário WHERE Email = ? AND Password = ?";

    try {
        // Preparar a consulta
        PreparedStatement statement = con.prepareStatement(sql);
        statement.setString(1, email);
        statement.setString(2, senha);

        // Executar a consulta
        ResultSet resultSet = statement.executeQuery();

        // Verificar se o usuário foi encontrado
        if (resultSet.next()){ 
           
            String nomeUsuario=resultSet.getString("Nome");
            folgas.aplicarPrivilegios(nomeUsuario);
            folgas.atualizarLabels(nomeUsuario);
            
            int funcionarioId=folgas.obterFuncionarioId(nomeUsuario);
            if (funcionarioId!=-1){
                System.out.println("FuncionarioId encontrado"+ funcionarioId);
                System.out.println("Nome do usuário"+nomeUsuario);
                System.out.println("Texto da label"+folgas.getJLabelNome().getText());
            }else{
                System.out.println("Funcionário Id não encontrado");
            }
            
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao autenticar usuário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }finally{
        try{
            resultSet.close();
            statement.close();
            con.close();
        }catch(Exception e){
            
        }
        
    }

    // Se chegou aqui, significa que ocorreu algum erro ou as credenciais são inválidas
    
    return null;
   }
   public JFormattedTextField getJFormattedTextFieldUtilizador(){
       return jFormattedTextFieldUtilizador;
   }
   public JPasswordField getJPasswordField(){
       return jPasswordField;
   }
   
   
   

   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    public javax.swing.JFormattedTextField jFormattedTextFieldUtilizador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelRegisto;
    private javax.swing.JPasswordField jPasswordField;
    // End of variables declaration//GEN-END:variables

    
}
